# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SurfMate_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'RxSwift'
pod 'RxCocoa'

  target 'SurfMate_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurfMate_iOSUITests' do
    # Pods for testing
  end

end
